In [56]:
# import numpy library as np
import numpy as np

### Task 1:

In [64]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Return sorted unique values that are in both a and b (a in b and b in a)
np.intersect1d(a,b)

array([2, 4])

###### Sources:
- https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.intersect1d.html

### Task 2:

In [58]:
# return values within a give interval and reshape them as a 5 x 3 array
np.arange(1,16).reshape((5,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

###### Sources:
- https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html
- https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

### Task 3:

In [59]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

In [62]:
# Return the sorted, unique values a or b but not a and b
np.setxor1d(a,b)

array([ 1,  6,  7,  8, 11, 14, 15, 19])

###### Sources: 
- https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.setxor1d.html

### Task 4:

In [65]:
# Total distance between NYC and Key West 
distance = 1548

n = 31

record = np.array(np.random.multinomial(distance, np.ones(n)/n, size=1)[0])

np.cumsum(record)

array([  45,   90,  129,  169,  222,  267,  324,  375,  430,  495,  543,
        576,  629,  681,  736,  787,  831,  872,  925,  977, 1035, 1079,
       1130, 1181, 1237, 1289, 1352, 1396, 1454, 1499, 1548])

###### Sources:
- http://sunny.today/generate-random-integers-with-fixed-sum/
- https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.cumsum.html

### Task 5: