In [131]:
import numpy as np

***

### Task 1

In [132]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

In [133]:
# creates new array containing only common values found in both arrays
c = np.intersect1d(a,b)

In [134]:
print(c)

[2 4]


- https://docs.scipy.org/doc/numpy/reference/generated/numpy.intersect1d.html
- https://docs.scipy.org/doc/numpy/reference/generated/numpy.unique.html

***

### Task 2

In [135]:
x = np.array([1,6,11,2,7,12,3,8,13,4,9,14,5,10,15])

In [136]:
# reshapes array based off inputted specifications, reshaping the array into a 5 x 3 array
x = x.reshape(5,3)

In [137]:
print(x)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


- https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

***

### Task 3

In [138]:
a = np.array([12,5,7,15,3,1,8])

b = np.array([14,6,3,11,19,12,5])

In [139]:
# create array of all values in a not found in b
not_common = [i for i in a if i not in b]

In [140]:
print(not_common)

[7, 15, 1, 8]


- https://stackoverflow.com/questions/40055835/removing-elements-from-an-array-that-are-in-another-array

***

### Task 4

- Suppose you have ridden a bicycle from New York City to Key West, Florida. 
- Your bicycle odometer shows the total miles you have travelled thus far, which you make a note of each day with paper and pencil. 
- Your first two entries might be ‘55’ and ‘120’, indicating that you rode your bike 55 miles on day 1 and 65 miles on day 2. 
- Your task is to create a NumPy array wherein you can record the cumulative miles you recorded each day during your trip. 
- Then use your Python skills to show the total miles that you rode each day. 
- Assume the trip took a total of 35 days and included at least 4 non-consecutive days where no cycling was possible due to either weather conditions or personal fatigue/soreness. 
- For the remaining 31 days, you would have covered the entire distance between NYC and Key West.
- Complete your work within your Jupyter Notebook for this assignment and be sure to include a writeup explaining your approach to this problem, including the ways in which you decided to make use of NumPy.

- 1547 miles between NYC and Key West
- take total miles and divide by number of days ridd

In [141]:
# create numpy array of length of the number of riding days and fill it with the total miles divided by number of days
ride = np.full(shape = 31,fill_value = 1547/31)

In [142]:
print(ride)

[49.90322581 49.90322581 49.90322581 49.90322581 49.90322581 49.90322581
 49.90322581 49.90322581 49.90322581 49.90322581 49.90322581 49.90322581
 49.90322581 49.90322581 49.90322581 49.90322581 49.90322581 49.90322581
 49.90322581 49.90322581 49.90322581 49.90322581 49.90322581 49.90322581
 49.90322581 49.90322581 49.90322581 49.90322581 49.90322581 49.90322581
 49.90322581]


In [143]:
# create numpy array containing 4 zeros to represent 4 days of no riding
no_ride = np.zeros(4)

In [144]:
# add the zeros to the ride array
distance = np.append(ride,no_ride)

In [145]:
# creates a cumulative sum of the values for each value (day) in the array
total_as_of = np.cumsum(distance)

print(total_as_of)

[  49.90322581   99.80645161  149.70967742  199.61290323  249.51612903
  299.41935484  349.32258065  399.22580645  449.12903226  499.03225806
  548.93548387  598.83870968  648.74193548  698.64516129  748.5483871
  798.4516129   848.35483871  898.25806452  948.16129032  998.06451613
 1047.96774194 1097.87096774 1147.77419355 1197.67741935 1247.58064516
 1297.48387097 1347.38709677 1397.29032258 1447.19354839 1497.09677419
 1547.         1547.         1547.         1547.         1547.        ]


***

### Task 5

In [146]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


numpy.ndarray

In [147]:
print(nyc_water)

[[   1979.  7102100.     1512.      213. ]
 [   1980.  7071639.     1506.      213. ]
 [   1981.  7089241.     1309.      185. ]
 [   1982.  7109105.     1382.      194. ]
 [   1983.  7181224.     1424.      198. ]
 [   1984.  7234514.     1465.      203. ]
 [   1985.  7274054.     1326.      182. ]
 [   1986.  7319246.     1351.      185. ]
 [   1987.  7342476.     1447.      197. ]
 [   1988.  7353719.     1484.      202. ]
 [   1989.  7344175.     1402.      191. ]
 [   1990.  7335650.     1424.      194. ]
 [   1991.  7374501.     1469.      199. ]
 [   1992.  7428944.     1369.      184. ]
 [   1993.  7506166.     1368.5     182. ]
 [   1994.  7570458.     1357.7     179. ]
 [   1995.  7633040.     1325.7     174. ]
 [   1996.  7697812.     1297.9     169. ]
 [   1997.  7773443.     1205.5     155. ]
 [   1998.  7858259.     1219.5     155. ]
 [   1999.  7947660.     1237.2     156. ]
 [   2000.  8008278.     1240.4     155. ]
 [   2001.  8024963.5    1184.      148. ]
 [   2002. 

***

In [148]:
# takes only the column with the data for yearly NYC consumption of water in millions of gallons per a day and selects only the max value from the data selected
max_consumption = np.amax(nyc_water[:,2])

print('The Maximum yearly NYC consumption of water in millions of gallons per a day is', max_consumption)

The Maximum yearly NYC consumption of water in millions of gallons per a day is 1512.0


- https://stackoverflow.com/questions/4455076/how-to-access-the-ith-column-of-a-numpy-multidimensional-array
- https://docs.scipy.org/doc/numpy/reference/generated/numpy.amax.html

***

In [149]:
# select column of data with years values and only show the unique values
calendar_years = np.unique(nyc_water[:,0])
# returns how many unique years there are in the column
count_years = np.size(calendar_years)

print('There are', count_years, 'years represented in this data set.')

There are 39 years represented in this data set.


- https://docs.scipy.org/doc/numpy/reference/generated/numpy.unique.html
- https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-16.php

***

In [150]:
# select column of data with water conumption values
water_consumption_per_capita = nyc_water[:,3]

In [151]:
# takes the mean of selected data
mean_water_consumption = np.mean(water_consumption_per_capita)

In [152]:
# takes standard deviation of selected data
std_water_consumption = np.std(water_consumption_per_capita)

In [153]:
print('the mean water consumption per capita is ', round(mean_water_conumption))

print('the standard deviation of water supply per capita is ', round(std_water_consumption))

the mean water consumption per capita is  160.0
the standard deviation of water supply per capita is  32.0


- https://www.google.com/search?q=np+mean+and+std&rlz=1C5CHFA_enUS821US821&oq=np.mean+and+&aqs=chrome.2.0j69i57j0l4.6481j0j7&sourceid=chrome&ie=UTF-8

***

In [154]:
# selects column of data relating to population and creates new array containing the difference of the value and the number before it
pop_diff = np.diff(nyc_water[:,1])
print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
